### ISSUE TITLE
写个wiki可以吗，从代码看不出怎么用

### ISSUE THREAD

**Issue by yangkkokk** [lshw/loongson_tools#2]
写个wiki可以吗，从代码看不出怎么用

**Comment by lshw** [comment]
用法要看CPU的手册的。
对寄存器写32位的数值（对齐）或者8位的数值

yangkkokk <notifications@github.com> 于 2019年5月17日周五 上午11:44写道：

**Comment by yangkkokk** [comment]
寄存器对应io那个地址表，还有复用表，然后搞个使用流程，就完美了

**Comment by lshw** [comment]
readme.md增加了几个文档链接。
